# Generated by Django 5.0.3 on 2024-04-02 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование курса')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('dataStart', models.DateTimeField(verbose_name='Время начала')),
                ('data_end', models.DateTimeField(verbose_name='Время конца')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('group_min_participants', models.PositiveIntegerField(verbose_name='Минимальное числов в группе')),
                ('group_man_participants', models.IntegerField(verbose_name='Максимальное числов в группе')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('content', models.TextField(blank=True, verbose_name='Описание курса')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='windowsOne.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Курсы',
                'verbose_name_plural': 'Курсы',
                'ordering': ['id'],
            },
        ),
    ]
